# POST /coffees
POST http://localhost:3000/coffees
Content-Type: application/json

{
  "name": "coffee#3",
  "brand": "Nest",
  "flavors": [
    "milk"
  ]
}

###
# GET /coffees

GET http://localhost:3000/coffees?limit=1&offset=10
Accept: application/json

###

### GET coffees/:id
GET http://localhost:3000/coffees/10

###

